# running info
exp_name: 'dfd_jpeg'
save_path: 'results/'


# model info
atk: 'sticker'
defenses: [
  # {
  #   'name': 'SpatialSmoothing',
  #   'args': [],
  #   'kwargs': {
  #     'window_size': 21
  #   }
  # },
  {
    'name': 'JPEG',
    'args': [],
    'kwargs': {
      'quality': 100
    }
  },
  # {
  #   'name': 'BitDepth',
  #   'args': [],
  #   'kwargs': {
  #     'compressed_bit': 6
  #   }
  # },
  # {
  #   'name': 'DAE',
  #   'args': [],
  #   'kwargs': {
  #     'model': 'dae',
  #     'res_output': True,
  #     'ckpt': '/data/guohaoxun/workspace/atk/AdvDefenseFramework/results/2022-12-07_00:07_dfd_dae_dae_res_trn/ckpts/ae_20.pth'
  #   }
  # },
]
model: 'efficientb7'
# model: 'mpvit'


# data info
batch_size: 4
data_path: 'b7'
# data_path: 'mpvit'
# data_path: 'multi'