# running info
exp_name: 'dfd_dae_dae'
save_path: 'results/'


# model info
atk: 'sticker'
defenses: [
  # {
  #   'name': 'SpatialSmoothing',
  #   'args': [],
  #   'kwargs': {
  #     'window_size': 21
  #   }
  # },
  # {
  #   'name': 'JPEG',
  #   'args': [],
  #   'kwargs': {
  #     'quality': 75
  #   }
  # },
  # {
  #   'name': 'BitDepth',
  #   'args': [],
  #   'kwargs': {
  #     'compressed_bit': 6
  #   }
  # },
  {
    'name': 'DAE',
    'args': [],
    'kwargs': {
      'model': 'dae',
      'res_output': False,
      'ckpt': '/data/guohaoxun/workspace/atk/AdvDefenseFramework/results/2022-12-07_00:06_dfd_dae_dae_trn/ckpts/ae_20.pth'
    }
  },
]
model: 'efficientb7'
# model: 'mpvit'


# data info
batch_size: 4
data_path: 'b7'
# data_path: 'mpvit'
# data_path: 'multi'